service: rest-api-dynamodb

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  stage: dev
  region: eu-central-1
  memorySize: 128

  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  hello:
    handler: src/hello.hello
    events:
      - http:
          path: hello
          method: get
          cors: true

  createUser:
    handler: src/createUser.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  deleteUser:
    handler: src/deleteUser.deleteUser
    events:
      - http:
          path: user/{userId}
          method: delete
          cors: true

  getUser:
    handler: src/getUser.getUser
    events:
      - http:
          path: user/{userId}
          method: get
          cors: true

  getUsers:
    handler: src/getUsers.getUsers
    events:
      - http:
          path: users
          method: get
          cors: true

resources:
  Resources:
    LohikaDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
