service: square-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  square:
    handler: handler.square
    events:
      - http:
          path: /square
          method: post
          cors: true
          
